### ISSUE TITLE
Calc's "@w" formatting should be expanded beyond "long" precision

### ISSUE THREAD

**Issue by rlwhitcomb** [rlwhitcomb/utilities#301]
For instance, `2**128@w` produces `minus eleven thousand, four hundred fifty-six` when the value really is `340,282,366,920,938,463,463,374,607,431,768,211,456`

**Comment by rlwhitcomb** [comment]
Can use `BigInteger.bitLength()` to compute the magnitude of the value in order to start somewhere reasonable in the table (instead of always searching from the top, and having lots of massive values to compute [probably using I_TEN.pow(n)]). Then "rangeValues" inside NumericUtil could be powers of ten, with a corresponding bit length (another array), so we only have to compute as many powers of ten as are necessary, which should then be cached....  _(this is started to sound complicated)_

**Comment by rlwhitcomb** [comment]
In fact we can get a fatal exception right now:
```
> 2**64-1@w
Exception in thread "main" java.lang.ArithmeticException: BigInteger out of long range
        at java.base/java.math.BigInteger.longValueExact(BigInteger.java:4818)
        at info.rlwhitcomb.calc.CalcObjectVisitor.visitExprStmt(Unknown Source)
        at info.rlwhitcomb.calc.CalcParser$ExprStmtContext.accept(Unknown Source)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at info.rlwhitcomb.calc.CalcObjectVisitor.internalVisitStatements(Unknown Source)
        at info.rlwhitcomb.calc.CalcObjectVisitor.visitStmtOrExpr(Unknown Source)
        at info.rlwhitcomb.calc.CalcParser$StmtOrExprContext.accept(Unknown Source)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at info.rlwhitcomb.calc.CalcObjectVisitor.internalVisitStatements(Unknown Source)
        at info.rlwhitcomb.calc.CalcObjectVisitor.visitProg(Unknown Source)
        at info.rlwhitcomb.calc.CalcParser$ProgContext.accept(Unknown Source)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at info.rlwhitcomb.calc.Calc.process(Unknown Source)
        at info.rlwhitcomb.calc.Calc.main(Unknown Source)
```

**Comment by rlwhitcomb** [comment]
All done now. The current limit for "getZillionName" is a base of one billion (or an exponent of three billion and three), which is far beyond the practical limits of numbers currently.
