### ISSUE TITLE
Missing class in Calc GUI (Java 16 related?)

### ISSUE THREAD

**Issue by rlwhitcomb** [rlwhitcomb/utilities#310]
```
Exception in thread "QueuedThread-1" java.lang.NoClassDefFoundError: info/rlwhitcomb/util/Exceptions
	at info.rlwhitcomb.util.QueuedThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: info.rlwhitcomb.util.Exceptions
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 1 more
```
when an error was encountered (entered "7,989+1,021")

**Comment by rlwhitcomb** [comment]
"manifest utilities.jar" shows that "info/rlwhitcomb/util/Exceptions.class  (3762 -> 1878 bytes)" is present in the .jar file...

**Comment by rlwhitcomb** [comment]
In REPL mode this worked fine, giving the expected error message.

**Comment by rlwhitcomb** [comment]
Never mind -- the "Start in:" location on the shortcut was wrong (Windows O/S).
