### ISSUE TITLE
Allow Calc to return functions from other functions

### ISSUE THREAD

**Issue by rlwhitcomb** [rlwhitcomb/utilities#33]
Would like to be able to do this:
`def f1($a, $b) = { $a + $b };
def f2($a, $b) = { $a * $b };
def f($c) = { $c ? f1 : f2 };
f(true)(1,2)
`
which at the moment gives the following exception:
Exception in thread "main" java.lang.ClassCastException: class info.rlwhitcomb.calc.FunctionScope cannot be cast to class info.rlwhitcomb.calc.FunctionDeclaration (info.rlwhitcomb.calc.FunctionScope and info.rlwhitcomb.calc.FunctionDeclaration are in unnamed module of loader 'app')
	at info.rlwhitcomb.calc.LValueContext.getLValue(LValueContext.java:417)
	at info.rlwhitcomb.calc.CalcObjectVisitor.getLValue(CalcObjectVisitor.java:3872)
	at info.rlwhitcomb.calc.CalcObjectVisitor.visitVarExpr(CalcObjectVisitor.java:1906)
...

**Comment by rlwhitcomb** [comment]
The parse tree for the example code with the current grammar is:
`(prog (stmt (defineStmt def (id f1) (formalParamList ( (formalParam $a) , (formalParam $b) )) = (stmtBlock { (stmtOrExpr (formattedExprs (exprStmt (expr (expr (var $a)) + (expr (var $b)))))) } \n))) (stmt (defineStmt def (id f2) (formalParamList ( (formalParam $a) , (formalParam $b) )) = (stmtBlock { (stmtOrExpr (formattedExprs (exprStmt (expr (expr (var $a)) * (expr (var $b)))))) } \n))) (stmt (defineStmt def (id f) (formalParamList ( (formalParam $c) )) = (stmtBlock { (stmtOrExpr (formattedExprs (exprStmt (expr (expr (var $c)) ? (expr (var (id f1))) : (expr (var (id f2))))))) } \n))) (stmt (stmtOrExpr (formattedExprs (exprStmt (expr (var (var (var (id f)) (actualParams ( (expr (value true)) ))) (actualParams ( (expr (value 1)) , (expr (value 2)) )))))))) (stmt (stmtOrExpr (emptyStmt \n))) (stmt (stmtOrExpr (emptyStmt \n))) (stmt (stmtOrExpr (emptyStmt \n))) <EOF>)`

**Comment by rlwhitcomb** [comment]
Actually, there are several problems:

- LValueContext needs to call "evaluateFunction" if it sees a FunctionScope (in the example, this would be the call, already setup) to "f(true)". This is easy to fix.
- Inside "evaluateFunction" we need to recognize that the reference to "f1" or "f2" is NOT a function call without parameters, but simply a function reference value that should be passed along.... THIS IS MUCH HARDER TO FIX because before we had real function parameters, this kind of "function call" without "()" was the only way to call functions, so we just did it.... Almost needs to be a mode in this one particular case NOT to do that....

**Comment by rlwhitcomb** [comment]
So, IF we make the assumption / convention that a "function call" to a function declared with parameters at the place where we have no parameters is just a reference to the function object and not an actual call to the function, then all is well!
